### ISSUE TITLE
Mapped Data in Swiper not rendering correctly.

### ISSUE THREAD

**Issue by trevans24** [kidjp85/react-id-swiper#404] opened 2020-03-01 20:05 UTC
react-id-swiper: ^3.0.0
swiper: ^5.3.6

When mapping data to the swiper component, as I have done in previous versions, the swiper renders all items ignoring the `slidesPerView`, `centeredSlides` parameters set. Here are my params:

```
const params = {
    containerClass: 'testimony-carousel',
    loop: true,
    lazy: true,
    rebuildOnUpdate: true,
    pagination: {
      el: '.swiper-pagination',
      dynamicBullets: true,
      clickable: true
    },
    centeredSlides: true,
    slidesPerView: 1
  }
```

inside the component it is set like this:
```
<Swiper {...params}>
      {
        data.testimonies.map((data, i) => (
          <Testimony key={i} data={data} />
        ))
      }
 </Swiper>
```
The styling has been imported as well, still just rendering all slides inside the swiper container

**Comment by alekslario** [comment] 2020-03-03 01:25
Might be Duplicate of #188

**Comment by mbretter** [comment] 2020-04-02 06:35
I encountered exactly the same issue, when using map() the console shows:
```
Children should be react element or an array of react element!!
```
when passing the elements directly as children, the Swiper works

**Comment by elias-garcia** [comment] 2020-04-12 01:32
I had the same problem @trevans24. Having a look at the [Swiper Docs](https://swiperjs.com/get-started/), I've figured out that they are wrapping each slide in a `div` with a class named `swiper-slide`. So this code works as expected:

```js
<Swiper {...params}>
  {edges.map(({ node: review }, index) => (
    <div className="swiper-slide" key={index}>
      <Review
        authorName={review.author.name}
        authorImage={review.author.image}
        rating={review.rating}
        comments={review.comments}
      />
    </div>
  ))}
</Swiper>
```

**Comment by dottodot** [comment] 2020-05-03 10:04
There seem to be an issue in 3.0.0 as when using a map, getSwiper isn't returning an instance but in 2.4.0 this is not a problem.

**Comment by kidjp85** [comment] 2020-06-26 07:51
For now, when you render map React Element, let make sure you have `swiper-slide` class name.  I will try to fix this issue in next release.

**Closed by kidjp85** 2020-06-26 07:51 UTC

**Comment by fahad-zakir** [comment] 2021-03-25 03:08
> I had the same problem @trevans24. Having a look at the [Swiper Docs](https://swiperjs.com/get-started/), I've figured out that they are wrapping each slide in a `div` with a class named `swiper-slide`. So this code works as expected:
> 
> ```js
> <Swiper {...params}>
>   {edges.map(({ node: review }, index) => (
>     <div className="swiper-slide" key={index}>
>       <Review
>         authorName={review.author.name}
>         authorImage={review.author.image}
>         rating={review.rating}
>         comments={review.comments}
>       />
>     </div>
>   ))}
> </Swiper>
> ```

Thank you! All I needed was that div

**Comment by animalbtw** [comment] 2022-12-01 16:37
Does it work now?

**Comment by Meta-Ben** [comment] 2022-12-26 01:12
Same problem here

**Comment by kusu0830** [comment] 2023-01-26 10:22
Here is the same problem.

**Comment by Suren-chiron** [comment] 2023-02-06 19:40
I tried this solution but the problem is still not solved
Swiper version: 9.0.3
